# Generated by Django 2.1.7 on 2019-03-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='artigo',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='categoria.Categoria'),
        ),
    ]
