# Generated by Django 2.1.7 on 2019-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('artigo', '0003_auto_20190326_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_artigo', to='categoria.Categoria'),
        ),
    ]
