# Generated by Django 2.1.7 on 2019-03-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0004_auto_20190327_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(to='categoria.Categoria'),
        ),
    ]
