# Generated by Django 2.1.7 on 2019-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0005_auto_20190327_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(related_name='artigos_categoria', to='categoria.Categoria'),
        ),
    ]
